# TensorFlow : Basic Operations

In [34]:
pip install tensorflow


Note: you may need to restart the kernel to use updated packages.


In [10]:
import tensorflow as tf

In [12]:
print(tf.__version__)

2.11.0


In [15]:
x=tf.constant(5.0)
print(x)

tf.Tensor(5.0, shape=(), dtype=float32)


In [21]:
x=tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [23]:
x=tf.zeros((2,2))
print(x)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [24]:
#tensor of ones 
x=tf.ones((2,2))
print(x)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [26]:
#identity matrix
x=tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [29]:
#generate random tensor from stdd normal distribution
x=tf.random.normal((2,2),mean=0, stddev=1)
print(x)

tf.Tensor(
[[-0.26041636 -2.0055716 ]
 [ 1.1530128  -0.5051578 ]], shape=(2, 2), dtype=float32)


In [30]:
#range function to generate tensors
x=tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [32]:
#delta parameter (step-size) in tensor
x=tf.range(start=1, limit=20, delta=3)
print(x)

tf.Tensor([ 1  4  7 10 13 16 19], shape=(7,), dtype=int32)


In [33]:
#converting data from int to float 
y=tf.cast(x,dtype=tf.float64)
print(y)

tf.Tensor([ 1.  4.  7. 10. 13. 16. 19.], shape=(7,), dtype=float64)
